### ISSUE TITLE
Visitors are able to view course articles without purchasing

### ISSUE THREAD

**Issue by BrooksPatton** [brooks-builds/lms#31]
![Image](https://github.com/brooks-builds/lms/assets/74931857/a1cf3138-fff8-4b77-abb8-1f516cc2fb67)

**Comment by albertlarsan68** [comment]
You must be logged in to access, but you do not need to have bought the course

**Comment by BrooksPatton** [comment]
Turns out that Hasura was set to allow any learner to access any course article as long as they had purchased one course. We updated the metadata for Hasura and pushed to prod. Things are working as expected now.
